int ni = 201;
int nj = 201;
double xa = 0.0;
double xb = 1.0;
double ya = 0.0;
double yb = 1.0;
double cfl = 0.8;
double U = 1.0;
double V = 2.0;
double tout = 0.2;
double mu = 100;
double dx;
double dy;
double dtx;
double dty;
double dt;
double time0;
double* x = nullptr;
double* y = nullptr;
double** f = new double* [ni];
double** fm1 = new double* [ni];
double** fm2 = new double* [ni];